#pragma once

#define XE_VERSION_STRING "MGE XE 0.18.0"
#define MGE_MAJOR_VERSION 4
#define MGE_MINOR_VERSION 18
#define MGE_BUILD_VERSION 0

#define MGE_SAVE_VERSION 47
#define MGE_DL_VERSION 7
#define MGE_MWSE_VERSION ((MGE_MAJOR_VERSION*0x10000)+(MGE_MINOR_VERSION*0x100)+MGE_BUILD_VERSION)
